apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::${AWS_ACCOUNT_ID}:user/aws-cli
      username: aws-cli
      groups:
        - system:masters
